/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    jacoco
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    maven {
        url =
            uri("https://makech-technology-879381274336.d.codeartifact.us-east-2.amazonaws.com/maven/makech-technology-maven-repository/")
        credentials {
            username = "aws"
            password = System.getenv("CODEARTIFACT_AUTH_TOKEN")
        }
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform)

    // JUnit 4 for Concordion compatibility
    testImplementation(libs.junit4)
    testRuntimeOnly(libs.junit.vintage.engine)

    // Concordion and testing dependencies
    testImplementation(libs.concordion)
    testImplementation(libs.assertj.core)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.junit.jupiter)
    testImplementation(libs.hamcrest)

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    implementation("org.json:json:20231013")
    implementation("org.makechtec.software:json_tree:3.0.0")
    implementation("org.bouncycastle:bcprov-jdk18on:1.78.1")
    implementation("de.mkammerer:argon2-jvm:2.11")
    implementation("org.makechtec.software:sql_support:3.0.3-BETA")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
    systemProperty("concordion.output.dir", "$buildDir/reports/spec")
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco"))
    }
}

jacoco {
    toolVersion = "0.8.11"
}

version = "1.5.0"

publishing {

    publications {


        publications.create<MavenPublication>("maven") {
            groupId = "org.makechtec.bearer_authentication"
            artifactId = "tools"
            version = project.version.toString()
            from(components["java"])
        }

    }

    repositories {
        maven {
            url =
                uri("https://makech-technology-879381274336.d.codeartifact.us-east-2.amazonaws.com/maven/makech-technology-maven-repository/")
            credentials {
                username = "aws"
                password = System.getenv("CODEARTIFACT_AUTH_TOKEN")
            }
        }
    }

}